title: Site

fields:
  title:
    label: Title
    type:  text

  metaDescription:
    label: Meta description
    type:  text
    width: 1/2

  metaKeywords:
    label: Meta keywords
    type:  text
    width: 1/2

  separator:
    type: line

  email:
    label: Email
    type: email
    width: 1/2

  phone:
    label: Phone
    type: text
    width: 1/2

  Facebook:
    label: Facebook
    type:  text
    width: 1/5

  Instagram:
    label: Instagram
    type:  text
    width: 1/5

  Twitter:
    label: Twitter
    type:  text
    width: 1/5

  LinkedIn:
    label: LinkedIn
    type:  text
    width: 1/5

  YouTube:
    label: YouTube
    type:  text
    width: 1/5

  separator:
    type: line

  # showcomments:
  #   label: Blog comments
  #   type: checkbox
  #   text: Show
  #   width: 1/4
